Handle that in newer version of FontTools needs to set self._tableCache
This prevents the error

[]python ./woff-info /tmp/aaa/f8.woff
Creating Info Report: /tmp/aaa/f8.woff...
Traceback (most recent call last):
  File "./woff-info", line 5, in <module>
    info.main()
  File "/Users/<username>/git/woffTools/Lib/woffTools/tools/info.py", line 276, in main
    html = reportInfo(font, fontPath)
  File "/Users/<username>/git/woffTools/Lib/woffTools/tools/info.py", line 242, in reportInfo
    writeFontFaceRule(font, fontPath, writer)
  File "/Users/<username>/git/woffTools/Lib/woffTools/tools/info.py", line 210, in writeFontFaceRule
    fontFaceRule = makeFontFaceRule(font, fontPath, doLocalSrc=False)
  File "/Users/<username>/git/woffTools/Lib/woffTools/tools/css.py", line 226, in makeFontFaceRule
    makeFontFaceFontFamily(font),
  File "/Users/<username>/git/woffTools/Lib/woffTools/tools/css.py", line 54, in makeFontFaceFontFamily
    familyName = _skimNameIDs(font, familyPriority)
  File "/Users/<username>/git/woffTools/Lib/woffTools/tools/css.py", line 189, in _skimNameIDs
    for nameRecord in font["name"].names:
  File "/Library/Python/2.7/site-packages/fontTools/ttLib/ttFont.py", line 376, in __getitem__
    if self._tableCache is not None:
  File "/Users/<username>/git/woffTools/Lib/woffTools/__init__.py", line 82, in __getattr__
    raise AttributeError(attr)
AttributeError: _tableCache